# Generated by Django 2.1.2 on 2019-01-02 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(help_text='permission key', max_length=255)),
                ('description', models.CharField(help_text='permission description', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date when Role is added.')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Date when Role is modified.')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/Disable this object')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short title of Role', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date when Role is added.')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Date when Role is modified.')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/Disable this object')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date when Role is added.')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Date when Role is modified.')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/Disable this object')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_group_name', to='web_app.RoleGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
