# Generated by Django 2.1.2 on 2019-01-05 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_permissions_rolegroup_rolepermission_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Permissions')),
                ('role_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_group_name', to='web_app.RoleGroup')),
            ],
        ),
    ]
